theme = "snazzy"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
cursorline = true

# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["ensure_selections_forward", "flip_selections", "extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.select]
X = ["ensure_selections_forward", "flip_selections", "extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"