[[language]]
name = "html"
formatter = { command = 'prettier' }

[[language]]
name = "json"
formatter = { command = 'prettier' }

[[language]]
name = "css"
formatter = { command = 'prettier' }

[[language]]
name = "javascript"
formatter = { command = 'prettier' }
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
formatter = { command = 'prettier' }
auto-format = true

[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
name = "rust"
autoformat = true
config = { check = { command = "clippy" } }
command = "rust-analyzer"

